import Head from "next/head";
import { FormContact } from "../components/FormContact";

const Contact = () => {
    return (
        <>
            <Head>
                <title>Contato</title>
                <meta name="theme-color" content="#4c00fd" />
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <FormContact />
        </>
    );
};

export default Contact;
