import Head from "next/head";
import { Hero } from "../components/Hero";
import { Menu } from "../components/Menu";

export default function Home() {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="theme-color" content="#4c00fd" />
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Menu />
            <Hero />
        </>
    );
}
